### ISSUE TITLE
Return value from code interpolation replaces placeholder text

### ISSUE THREAD

**Issue by Einlar** [draivin/hsnips#3]
The following snippet contains two placeholders: `$1` on the first line, and `$2` on the last one. Between `$1` and `$2` there is a dynamic code that prints 'c' if the first character typed in `$2` is '-', and 'd' otherwise. 

    snippet mm "test" A
    \$$1\$
    ``if (t[1] && t[1][0] == '-') { rv = 'c' } else { rv = 'd' }``
    $2
    endsnippet

If `$1`, `$2` and the code interpolation are all on different lines, the snippet works as expected. However, if line breaks are removed, like in the following:

    snippet mm "test" A
    \$$1\$``if (t[1] && t[1][0] == '-') { rv = 'c' } else { rv = 'd' }``$2
    endsnippet

then, the return value `rv` interferes with `$1` and `$2`, and the snippet does not work anymore. 

This snippet actually comes by adapting code from a UltiSnips snippet:

    snippet mk "Math" wA
    $${1}$`!p
    if t[2] and t[2][0] not in [',', '.', '?', '-', ' ']:
        snip.rv = ' '
    else:
        snip.rv = ''
    `$2
    endsnippet

which is used in [https://castel.dev/post/lecture-notes-1/](https://castel.dev/post/lecture-notes-1/) and works as expected in Vim. Is it possible to replicate this behavior in Visual Studio Code?

**Comment by draivin** [comment]
Fixed by 233f539, the behavior matches ultisnips now, thanks for the report!

**Comment by Einlar** [comment]
I think that there is something that still doesn't work. 
Referring to the previous example, now `$2` can be put on the same line of the code block:

    snippet mm "test" A
    \$$1\$
    ``if (t[1] && t[1][0] == '-') { rv = '\bc' } else { rv = 'd' }``$2
    endsnippet

and it works as expected. However:

    snippet mm "test" A
    \$$1\$ ``if (t[1] && t[1][0] == '-') { rv = '\bc' } else { rv = 'd' }``$2
    endsnippet

still does not work. If there aren't spaces between `\$$1\$` and ``if the snippet prints only a $ (instead of $$). If there are spaces, the snippets correctly prints $$, but the return value isn't updated anymore.

**Comment by draivin** [comment]
Ops, my bad, it seems I was counting the escaped dollar signs as two characters, so the snippet handler thought the placeholders were at different positions, can you check if it is working now?

**Comment by draivin** [comment]
By the way, what is the `\b` for inside your return values?

**Comment by Einlar** [comment]
Almost!
Now it updates correctly if there is at least a blank space between the \$$1\$ and ``if, like in this:

   snippet mm "test" A
   \$$1\$ ``if (t[1] && t[1][0] == '-') { rv = '' } else { rv = ' ' }``$2
   endsnippet

but it doesn't work without the space, and still prints only the first \$, ignoring all the rest (apparently even the $2 placeholder does not work in this case): 

   snippet mm "test" A
   \$$1\$``if (t[1] && t[1][0] == '-') { rv = '' } else { rv = ' ' }``$2
   endsnippet

It is in fact a problem of escaping, as if I use another character (e.g. 'a' instead of '\$') it works, even without spaces:

   snippet mm "test" A
   a$1a``if (t[1] && t[1][0] == '-') { rv = '' } else { rv = ' ' }``$2
   endsnippet

> By the way, what is the `\b` for inside your return values?

I was trying to find a workaround by removing the added space with a \b (obviously it doesn't work, nor I didn't expect it to really).

**Comment by Einlar** [comment]
I found a workaround by simply putting the second $ inside the return value, like in the following:

    snippet mm "test" A
    \$$1``if (t[1] && ",-.? ".indexOf(t[1][0]) >= 0) { rv = '$' } else { rv = '$ ' }``$2
    endsnippet

Now it perfectly replicates the behavior I had in UltiSnips.
By the way thanks for the fast updates! I really needed an extension like this, as I find Visual Studio Code much more easier than Vim.

**Comment by draivin** [comment]
That's weird, the code you supplied on your previous comment works as expected over here, did you update the extension?

**Comment by Einlar** [comment]
I updated it to 0.0.14. Now I tried to reload VS Code, and in fact it works even with the original code. Thanks!
