### ISSUE TITLE
Snippets with tab completion don't work (regex)

### ISSUE THREAD

**Issue by UtahKemeran** [draivin/hsnips#55]
```vim
global
function math(context) {
    return context.scopes.some(s => s.startsWith("meta.math"));
}
endglobal

context math(context)
snippet `(?<!\\)(sin|cos|arccot|arccos|arcsin|sinh|cosh|cot|csc|ln|log|exp|star|perp)` "ln" 
\\``rv = m[1]``
endsnippet
```
This snippet only works when adding the flag `A`, however, I don't want it to expand instantly but when hitting tab, why?
This problem also occurs for many other snippets which I want to expand with tab.

**Comment by SASY-2333** [comment]
My answer in the issue #56 may help you.
The Link: https://github.com/draivin/hsnips/issues/56#issuecomment-917838850

**Comment by draivin** [comment]
Fixed in https://github.com/draivin/hsnips/pull/76.

**Comment by sffred** [comment]
> My answer in the issue #56 may help you. The Link: [#56 (comment)](https://github.com/draivin/hsnips/issues/56#issuecomment-917838850)

It solves the problem for me in most situations but the completion still doesn't shows when I am editing a .ipynb file using the jupyter notebook.
